from __future__ import annotations

WEATHER_MAPPING = {
    0: "Clear",
    1: "Mostly Clear",
    2: "Partly Cloudy",
    4: "Clouds",
    5: "Foggy",
    6: "Light Rain",
    7: "Rain",
    8: "Heavy Rain",
    9: "Drizzle",
    10: "Thunderstorm",
    11: "Snow",
    13: "Light Snow",
    14: "Overcast",
    17: "Haze",
    19: "Windy",
    20: "Storm",
}

TRAVEL_MODE_MAPPING = {
    -1: "unknown",
    0: "walk",
    1: "bike",
    2: "car",
    3: "transit",
    4: "ride",
    5: "unknown",
}

REGION_TO_STATE = {
    580: ("New York", "NY", "Middle Atlantic"),
    581: ("New Jersey", "NJ", "Middle Atlantic"),
    582: ("Pennsylvania", "PA", "Middle Atlantic"),
    583: ("Massachusetts", "MA", "New England"),
    584: ("Connecticut", "CT", "New England"),
    585: ("Rhode Island", "RI", "New England"),
    586: ("New Hampshire", "NH", "New England"),
    587: ("Vermont", "VT", "New England"),
    588: ("Maine", "ME", "New England"),
    600: ("Florida", "FL", "South Atlantic"),
    601: ("Georgia", "GA", "South Atlantic"),
    602: ("North Carolina", "NC", "South Atlantic"),
    603: ("Virginia", "VA", "South Atlantic"),
    604: ("Maryland", "MD", "South Atlantic"),
    605: ("South Carolina", "SC", "South Atlantic"),
    606: ("Delaware", "DE", "South Atlantic"),
    607: ("West Virginia", "WV", "South Atlantic"),
    608: ("District of Columbia", "DC", "South Atlantic"),
    610: ("Texas", "TX", "West South Central"),
    611: ("Oklahoma", "OK", "West South Central"),
    612: ("Arkansas", "AR", "West South Central"),
    613: ("Louisiana", "LA", "West South Central"),
    620: ("Tennessee", "TN", "East South Central"),
    621: ("Kentucky", "KY", "East South Central"),
    622: ("Alabama", "AL", "East South Central"),
    623: ("Mississippi", "MS", "East South Central"),
    700: ("Illinois", "IL", "East North Central"),
    701: ("Ohio", "OH", "East North Central"),
    702: ("Michigan", "MI", "East North Central"),
    703: ("Indiana", "IN", "East North Central"),
    704: ("Wisconsin", "WI", "East North Central"),
    710: ("Minnesota", "MN", "West North Central"),
    711: ("Missouri", "MO", "West North Central"),
    712: ("Iowa", "IA", "West North Central"),
    713: ("Kansas", "KS", "West North Central"),
    714: ("Nebraska", "NE", "West North Central"),
    715: ("South Dakota", "SD", "West North Central"),
    716: ("North Dakota", "ND", "West North Central"),
    800: ("California", "CA", "Pacific"),
    801: ("Washington", "WA", "Pacific"),
    802: ("Oregon", "OR", "Pacific"),
    803: ("Hawaii", "HI", "Pacific"),
    804: ("Alaska", "AK", "Pacific"),
    810: ("Arizona", "AZ", "Mountain"),
    811: ("Colorado", "CO", "Mountain"),
    812: ("Nevada", "NV", "Mountain"),
    813: ("Utah", "UT", "Mountain"),
    814: ("New Mexico", "NM", "Mountain"),
    815: ("Idaho", "ID", "Mountain"),
    816: ("Montana", "MT", "Mountain"),
    817: ("Wyoming", "WY", "Mountain"),
}

TIER_LABELS = ["Rural", "Suburban", "Mid-size City", "Major City", "Metropolis"]
CATEGORICAL_COLS = ["weather_label", "travel_mode_label", "census_division", "region_tier"]
NUMERICAL_COLS = ["region_freq", "poi_freq", "month", "hour", "day_of_week"]
ALL_FEATURES = CATEGORICAL_COLS + NUMERICAL_COLS
